apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo-deployment
  namespace: demo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      name: nginx-demo-pod
      labels:
        app: nginx-demo
    spec:
      containers:
        - name: nginx-demo-container
          image: nginx
          ports:
            - containerPort: 80
