apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
  # replace with namespace where provisioner is deployed
  namespace: nfs-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: vmlocal.co.in/nfs
            - name: NFS_SERVER
              value: 172.x.x.x
            - name: NFS_PATH
              value: /backup_data/KVM/data/nfs_share/kubedata   ###You can Specify NFS directory from custom NFS exports
      volumes:
        - name: nfs-client-root
          nfs:
            server: 172.16.16.1
            path: /backup_data/KVM/data/nfs_share/kubedata     ###You can Specify NFS directory from custom NFS exports
