apiVersion: apps/v1
kind: Deployment
metadata:
  name: mykustomwebapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mykustomwebapp  # <- fixed to match the label below
  template:
    metadata:
      labels:
        app: mykustomwebapp  # <- matches the selector
    spec:
      containers:
      - name: mycontainer
        image: "tejaspandhare/pythonwebdemo"
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: mykustom-configmap
        resources:
          requests:
            memory: "16Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
