apiVersion: apps/v1
kind: Deployment
metadata:
  name: mykustomwebapp
  namespace: webapps
spec:
  replicas: 1
  template:
    spec: # Pod spec
      containers:
      - name: mycontainer
        image: "tejaspandhare/pythonwebdemo"
        ports:
        - containerPort: 80i
        envFrom:
        - configMapRef:
            name: mykustom-map
        resources:
          requests:
            memory: "16Mi" 
            cpu: "50m"    # 500milliCPUs (1/2 CPU)
          limits:
            memory: "128Mi"
            cpu: "100m"
