
resources: 
- deployment.yaml
- service.yaml

commonLabels:
  app: mykustomwebapp

commonAnnotations:
  app: mykustom-annontations

namePrefix:
  kustom-

nameSuffix:
  -v1

configMapGenerator:
- name: mykustom-configmap
  env: config.properties
