apiVersion: v1
kind: Service
metadata:
  name: ansibledemo1-clusterip
  namespace: pipelines
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: jenkinsansiblenonroot
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
