apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo-deployment
  namespace: pipelines
  annotations:
    kubernetes.io/change-cause: "Updating to alipine version"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      name: nginx-demo-pod
      labels:
        app: nginx-demo
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
