apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: vmlocal.co.in/nfs
parameters:
  archiveOnDelete: "false"
