apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: automation-demo1-wildcard-vmlocal-co-in
spec:
  secretName: automation-demo1-wildcard-vmlocal-co-in-tls
  renewBefore: 240h
  dnsNames:
  - '*.vmlocal.co.in'
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
