---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkinsansible-nonroot-ansibledemo1-pv-volume
  namespace: pipelines
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: managed-nfs-storage-class
  nfs:
    server: 172.16.16.1
    path: /backup_data/KVM/data/nfs_share/kubedata/jenkins_with_ansible_nonroot_ansibledemo1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kworker1       
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkinsansible-nonroot-ansibledemo1-pv-claim
  namespace: pipelines
spec:
  storageClassName: managed-nfs-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
