apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx-demo
  name: nginx-demo-deploy
  namespace: demotest
spec:
  replicas: 1
  selector:
    matchLabels:
      run: test-namespace
  template:
    metadata:
      labels:
        run: nginx-demo
    spec:
      containers:
      - image: nginx
        name: nginx-demo
